services:
  - type: web
    name: text-summarization-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    branch: main
    region: oregon
